.\" Manpage for dockup.
.TH man 1 "11 July 2020" "1.0" "dockup man page"
.SH NAME
dockup \- update existing docker containers with a new image
.SH SYNOPSIS
.BI "dockup -c \fICONTAINER\fR -i \fIIMAGE\fR [OPTIONS]..."
.SH DESCRIPTION
\fBdockup\fR is a tool for rebuilding docker containers with new/different images. It has the capability to start the rebuilt container if it was running prior to \fBdockup\fR being executed, whether that be via systemd or simply docker start.
.SH OPTIONS
.TP
\fB\-a\fR, \fB\-\-args\fR <arguments>
The arguments to build the container with. If using \fB\-p\fR, volume mounts are redundant.
.TP
\fB\-c\fR, \fB\-\-container\fR <container>
The container on which to operate
.TP
\fB\-h\fR, \fB\-\-help\fR
Prints a basic usage and exits
.TP
\fB\-i\fR, \fB\-\-image\fR <image>
The image to rebuild the container with. The latest version will be pulled
.TP
\fB\-p\fR, \fB\-\-preserve\-volumes\fR
Preserves the containers volume mounts by mounting them to a temporary container (busybox)
.TP
\fB\-s\fR, \fB\-\-systemd\fR <service>
The systemd service that manages the container
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Prints verbose output
.TP
\fB\-V\fR, \fB\-\-version\fR
Show version information and exit
.SH EXAMPLE
The examples shown below demonstrate the use of \fBdockup\fR.
.PP

The following command updates a jellyfin container, preserving volume mounts. If the container is running when \fBdockup\fR is executed, the rebuilt container will be started. The options in the string after \fB\-a\fR will be used when building the container.
.in +4n
.EX
.RB "dockup \-\-container jellyfin \-\-image jellyfin/jellyfin \-\-preserve\-volumes \-a \(dq\-\-user 1000:1000 \-\-net=host \-\-restart=unless\-stopped\(dq"
.EE
.in

.PP

The command below updates an existing nginx container, preserving volume mounts and exposes both ports 80 and 443 from the host to the rebuilt container. It interacts with systemd to start/restart the service as needed.
.in +4n
.EX
.RB "dockup \-c webserver \-i nginx \-p \-v \-s nginx.service \-a \(dq\-p 80:80 \-p 443:443\(dq"
.EE
.in

.SH AUTHOR
Evan Shipman
.SH BUGS
No known bugs.
Report any bugs to <https://github.com/eshipman/docker-utilities>.
.SH COPYRIGHT
Copyright \(co 2020 Evan Shipman
License MIT: <https://opensource.org/licenses/MIT>.
.SH SEE ALSO
docker(1), systemd(1)
